num_episodes: 20000
batch_size: 32
train_iters: 100
gamma: 0.9
eps_start: 1.0
eps_end: 0.1
eps_decay: 1.e+7
lr: 0.0003
hidden_size: !!python/tuple
  - 1000
  - 500
target_update: 1.e+3
memory: 1.e+5
test_episodes: 15
