num_cycles: 10000
warmup_period: 500
joint_period: 500
batch_size: 32
test_episodes: 15
num_tasks: 2
task_ER: 1.e+5
retrain_master_episodes: 10000
remind_freq: 10

master_eps_decay: 340
master_eps_start: 1.0
master_eps_end: 0.1
master_target_update: 20
master_lr: 0.01
master_gamma: 0.85
master_ER: 3000
master_hidden_size: !!python/tuple
  - 1000
  - 500
n_sub_policies: 3
sub_eps_decay: 1.e+6
sub_eps_start: 0.8
sub_eps_end: 0.1
sub_target_update: 1.e+3
sub_lr: 0.00025
sub_gamma: 0.85
sub_hidden_size: !!python/tuple
  - 1000
  - 500
