#!/bin/bash

#SBATCH --time=10:00:00
#SBATCH --partition=gpu
#SBATCH --gres=gpu:v100:1
#SBATCH --mem=20GB
#SBATCH --output=Job-%j-q_learning.log
#SBATCH --mail-type=FAIL,END
#SBATCH --mail-user=d.cabo.golvano@student.rug.nl

module purge
module load Python
module load CUDA
echo "Modules loaded"
module list

echo "Creating venv"
python -m venv venv
source venv/bin/activate
pip install --upgrade pip
pip install --upgrade setuptools
pip install -e /home/s3736555/Household-env
pip install -e .

echo "Starting execution"
python thesis_hrl/run_q_learning.py --num_episodes 10000 --batch_size 128 --lr 1e-2 --eps_decay 500
#python thesis_hrl/run_q_learning.py --num_episodes 20 --test 128_0.999_0.9_0.05_500_10_0.01

