#!/bin/bash

#SBATCH --time=23:55:00
#SBATCH --partition=gpu
#SBATCH --gres=gpu:v100:1
#SBATCH --mem=32GB
#SBATCH --output=Job-%j-q_learning.log
#SBATCH --mail-type=FAIL,END
#SBATCH --mail-user=d.cabo.golvano@student.rug.nl

module purge
module load Python
module load CUDA
echo "Modules loaded"
module list

# echo "Creating venv"
# python -m venv venv
source venv/bin/activate
# pip install --upgrade pip
# pip install --upgrade setuptools
# pip install -e /home/s3736555/Household-env
# pip install -e .

hp="hyperparam_02.yaml"
weights="hyperparam_01"
echo "Starting execution for $hp"

python -u thesis_hrl/train_new_task.py --hyperparam $hp --weights $weights
