#!/bin/bash

#SBATCH --time=10:00:00
#SBATCH --partition=gpu
#SBATCH --gres=gpu:v100:1
#SBATCH --mem=20GB
#SBATCH --output=Job-%j-q_learning.log
#SBATCH --mail-type=FAIL,END
#SBATCH --mail-user=d.cabo.golvano@student.rug.nl

module purge
module load Python
module load CUDA
echo "Modules loaded"
module list

#echo "Creating venv"
#python -m venv venv
source venv/bin/activate
pip install --upgrade pip
pip install --upgrade setuptools
pip install -e /home/s3736555/Household-env
pip install -e .

echo "Starting execution"
python thesis_hrl/run_q_learning.py --num_episodes 100000 --batch_size 16 --eps_decay 1e5 --target_update 1e4 --lr 1e-4
