#!/bin/bash

#SBATCH --time=23:55:00
#SBATCH --partition=gpu
#SBATCH --gres=gpu:v100:1
#SBATCH --mem=20GB
#SBATCH --output=Job-%j-q_learning.log
#SBATCH --mail-type=FAIL,END
#SBATCH --mail-user=d.cabo.golvano@student.rug.nl

module purge
module load Python
module load CUDA
echo "Modules loaded"
module list

# echo "Creating venv"
# python -m venv venv
source venv/bin/activate
# pip install --upgrade pip
# pip install --upgrade setuptools
# pip install -e /home/s3736555/Household-env
# pip install -e .

echo "Starting execution"

#OG #python thesis_hrl/run_q_learning.py --num_episodes 150000 --batch_size 32 --eps_decay 2e5 --target_update 1e4 --lr 0.00025 --eps_start 1 --eps_end 0.1 --gamma 0.99 --memory 1000000
python thesis_hrl/run_q_learning.py --num_episodes 150000 --batch_size 16 --eps_decay 2e5 --target_update 1e4 --lr 0.00025 --eps_start 1 --eps_end 0.1 --gamma 0.99 --memory 1000000
python thesis_hrl/run_q_learning.py --num_episodes 150000 --batch_size 32 --eps_decay 2e5 --target_update 1e4 --lr 1e-4 --eps_start 1 --eps_end 0.1 --gamma 0.99 --memory 1000000
python thesis_hrl/run_q_learning.py --num_episodes 150000 --batch_size 32 --eps_decay 5e4 --target_update 1e4 --lr 0.00025 --eps_start 1 --eps_end 0.1 --gamma 0.99 --memory 1000000
python thesis_hrl/run_q_learning.py --num_episodes 150000 --batch_size 16 --eps_decay 2e5 --target_update 5e3 --lr 0.00025 --eps_start 1 --eps_end 0.1 --gamma 0.99 --memory 1000000

# OLD ones
# python thesis_hrl/run_q_learning.py --num_episodes 150000 --batch_size 8 --eps_decay 45e3 --target_update 3e4 --lr 1e-4 --eps_end 0.05 --gamma 0.999
# python thesis_hrl/run_q_learning.py --num_episodes 150000 --batch_size 16 --eps_decay 45e3 --target_update 3e4 --lr 1e-4 --eps_end 0.05 --gamma 0.85
# python thesis_hrl/run_q_learning.py --num_episodes 150000 --batch_size 16 --eps_decay 45e3 --target_update 3e4 --lr 1e-4 --eps_end 0.05 --gamma 0.95
# python thesis_hrl/run_q_learning.py --num_episodes 150000 --batch_size 16 --eps_decay 45e3 --target_update 2e4 --lr 1e-4 --eps_end 0.05 --gamma 0.85
# python thesis_hrl/run_q_learning.py --num_episodes 150000 --batch_size 16 --eps_decay 45e3 --target_update 3e4 --lr 1e-4 --eps_end 0.1 --gamma 0.999
# python thesis_hrl/run_q_learning.py --num_episodes 150000 --batch_size 16 --eps_decay 6e4 --target_update 3e4 --lr 1e-4 --eps_end 0.05 --gamma 0.9
# python thesis_hrl/run_q_learning.py --num_episodes 150000 --batch_size 16 --eps_decay 1e5 --target_update 3e4 --lr 1e-4 --eps_end 0.05 --gamma 0.99
# python thesis_hrl/run_q_learning.py --num_episodes 150000 --batch_size 16 --eps_decay 6e4 --target_update 1e4 --lr 1e-4 --eps_end 0.05 --gamma 0.99
# python thesis_hrl/run_q_learning.py --num_episodes 100000 --batch_size 16 --eps_decay 8e4 --target_update 5e3 --lr 1e-4 --eps_end 0.1
# python thesis_hrl/run_q_learning.py --num_episodes 100000 --batch_size 16 --eps_decay 8e4 --target_update 2e3 --lr 1e-5 --eps_end 0.1
# python thesis_hrl/run_q_learning.py --num_episodes 200000 --batch_size 16 --eps_decay 1e5 --target_update 1e4 --lr 1e-4 --eps_end 0.1
# python thesis_hrl/run_q_learning.py --num_episodes 200000 --batch_size 16 --eps_decay 1e5 --target_update 1e4 --lr 3e-4 --eps_end 0.1
# python thesis_hrl/run_q_learning.py --num_episodes 200000 --batch_size 32 --eps_decay 1e5 --target_update 1e4 --lr 1e-4 --eps_end 0.1
# python thesis_hrl/run_q_learning.py --num_episodes 200000 --batch_size 32 --eps_decay 1e5 --target_update 1e4 --lr 3e-4 --eps_end 0.1
# python thesis_hrl/run_q_learning.py --num_episodes 200000 --batch_size 64 --eps_decay 5e4 --target_update 1e4 --lr 1e-4 --eps_end 0.1
# python thesis_hrl/run_q_learning.py --num_episodes 100000 --batch_size 16 --eps_decay 45e3 --target_update 3e4 --lr 1e-4 --eps_end 0.1
# python thesis_hrl/run_q_learning.py --num_episodes 100000 --batch_size 16 --eps_decay 5e4 --target_update 1e4 --lr 1e-4 --eps_end 0.1
# python thesis_hrl/run_q_learning.py --num_episodes 100000 --batch_size 16 --eps_decay 1e5 --target_update 1e4 --lr 1e-4 --eps_end 0.1
# python thesis_hrl/run_q_learning.py --num_episodes 100000 --batch_size 16 --eps_decay 1e5 --target_update 1e4 --lr 1e-3 --eps_end 0.1
# python thesis_hrl/run_q_learning.py --num_episodes 100000 --batch_size 16 --eps_decay 1e5 --target_update 6e3 --lr 1e-4 --eps_end 0.1
# python thesis_hrl/run_q_learning.py --num_episodes 100000 --batch_size 32 --eps_decay 45e3 --target_update 3e4 --lr 1e-4
# python thesis_hrl/run_q_learning.py --num_episodes 100000 --batch_size 32 --eps_decay 45e3 --target_update 3e4 --lr 1e-5
# python thesis_hrl/run_q_learning.py --num_episodes 100000 --batch_size 16 --eps_decay 1e5 --target_update 6e3 --lr 1e-4
# python thesis_hrl/run_q_learning.py --num_episodes 100000 --batch_size 16 --eps_decay 3e5 --target_update 1e5 --lr 1e-3
# python thesis_hrl/run_q_learning.py --num_episodes 100000 --batch_size 16 --eps_decay 3e5 --target_update 1e5 --lr 1e-4
